alias backup="echo 'this is not nas - ssh in and run backup'"
alias checkrr="find . -type f -not -name \"*-*-*.*\""
alias chgrp="chgrp -c"
alias chmod="chmod -c"
alias chown="chown -c"
alias cp="cp -v"
alias dmesg="checkroot dmesg -T"
alias fixscriptsperms="chmod -Rc u+rwx,go-w+rx $HOME/Scripts"
alias fixsynergy="pkill synergy;sleep 1;synergyc 172.21.2.3"
alias grep="grep --color=auto"
alias ip="ip -c"
alias ipinfo="curl ipinfo.io"
alias ipq="ip -br"
alias lsblk="lsblk -o NAME,SIZE,FSAVAIL,FSUSE%,FSTYPE,MOUNTPOINT,LABEL"
alias minimal='bash -c "$(curl http://sc.tralce.com/minimal.sh)"'
alias mv="mv -v"
alias nossh="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
alias nosshnokey="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o PasswordAuthentication=yes -o PreferredAuthentications=keyboard-interactive,password -o PubkeyAuthentication=no"
alias poweroff="checkroot poweroff"
alias qmin='bash -c "SILENT= $(curl http://sc.tralce.com/minimal.sh)"'
alias reboot="checkroot reboot"
alias rename="rename -v"
alias resetperms="chmod -R a-x+X,ug+rw,o-w+r"
alias sdnow="checkroot systemctl --now disable"
alias senow="checkroot systemctl --now enable"
alias shred="shred -vun50"
alias sync_size="watch grep -e Dirty: -e Writeback: /proc/meminfo"
alias syncscripts-I="unison -terse -ui text -auto -ignorearchives ssh://tralce@eclart.xyz:222//home/tralce/Scripts $HOME/Scripts"
alias syncscripts="unison -terse -ui text -auto ssh://tralce@eclart.xyz:222//home/tralce/Scripts $HOME/Scripts"
alias tb="nc tb.tralce.com 9999"
alias tmin='bash -c "TRUST= $(curl http://sc.tralce.com/minimal.sh)"'
alias tmx="tmux_or_screen.sh"
alias top10="find -type f -printf '%s %p\n'| sort -nr | head -10"
alias topextensions="find . -type f | sed -n 's/..*\.//p' | sort | uniq -c | sort -nr"
alias updatedb="checkroot updatedb"
alias vupd="vim +PlugInstall +PlugUpdate! +PlugUpgrade +PlugClean +qa"
alias vw="vim -c WikiIndex"
alias wasabi="aws --profile wasabi --endpoint-url=https://s3.wasabisys.com s3"
alias wasabidgc="aws --profile wasabi-dgc --endpoint-url=https://s3.wasabisys.com s3"
alias whatismyip="dig +short myip.opendns.com @resolver1.opendns.com"
test -f /etc/issue && alias piversion="grep -q Revision /proc/cpuinfo && curl -L perturb.org/rpi?rev=$(awk '/^Revision/ { print $3 }' /proc/cpuinfo)"
test -f ~/.acme.sh/acme.sh && alias acme.sh="~/.acme.sh/acme.sh"
test -f ~/Documents/binaries/startvpn.sh && alias startvpn="bash ~/Documents/binaries/startvpn.sh"
test -f ~/topgrade && alias topgrade="~/topgrade"
